server:
  port: 8002
spring:
#  autoconfigure:
#    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    druid:
#      stat-view-servlet:
#        enabled: true
#        login-username: admin
#        login-password: 123456
#      web-stat-filter:
#        enabled: true
  shardingsphere:
    props:
      sql-show: true
    mode:
      type: Memory
    datasource:
#      common:
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        #初始连接数
#        initial-size: 6
#        #最小空闲连接数
#        min-idle: 3
#        #最大连接数
#        max-active: 20
#        #连接超时时间
#        max-wait: 600000
#        #检测间隔时间，检测需要关闭的空闲连接
#        time-between-eviction-runs-millis: 60000
#        #一个连接在池中的最小生存时间
#        min-evictable-idle-time-millis: 300000
#        test-while-idle: true
#        test-on-borrow: false
#        test-on-return: false
#        #打开PSCache
#        pool-prepared-statements: true
#        #指定每个连接上的PSCache大小
#        max-pool-prepared-statement-per-connection-size: 20
#        #统计拦截器：wall:用于防火墙、stat:用于统计sql、slf4j:用于日志
#        filter:
#          wall:
#            enabled: true
#            config:
#              multi-statement-allow: true
#              none-base-statement-allow: true
#          stat:
#            enabled: true
#            log-slow-sql: true
#            slow-sql-millis: 20
#            merge-sql: true
#          slf4j:
#            enabled: true
#            statement-log-enabled: true
#            statement-logger-name: BMP
#            statement-sql-pretty-format: true
      names: master,slave
      master:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://139.196.112.185:3307/TEST-01?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&useSSL=false
        username: root
        password: 123456
        pool-name: CRS-HikariPool-1
        #最小连接数
        minimum-idle: 10
        #最大连接数
        maximum-pool-size: 20
        #当前池内连接数大于最小连接数时触发idle-timeout参数，超时回收多余连接
        idle-timeout: 1800000
        #当前池内连接数小于等于最小连接数时触发max-lifetime参数，超时回收该连接
        max-lifetime: 3600000
        #连接超时时间
        connection-timeout: 60000
        #测试连接sql
        connection-test-query: SELECT 1
      slave:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://139.196.112.185:3308/TEST-01?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&useSSL=false
        username: root
        password: 123456
        pool-name: CRS-HikariPool-2
        #最小连接数
        minimum-idle: 10
        #最大连接数
        maximum-pool-size: 20
        #当前池内连接数大于最小连接数时触发idle-timeout参数，超时回收多余连接
        idle-timeout: 1800000
        #当前池内连接数小于等于最小连接数时触发max-lifetime参数，超时回收该连接
        max-lifetime: 3600000
        #连接超时时间
        connection-timeout: 60000
        #测试连接sql
        connection-test-query: SELECT 1
      enabled: true
    rules:
      readwrite-splitting:
        data-sources:
          load-balancers:
            roundRobin:
              type: ROUND_ROBIN
          master-slave:
            props:
              auto-aware-data-source-name: master
              load-balancers-names: roundRobin
              read-data-source-names: slave
              write-data-source-name: master
            type: Static
#    rules:
#      readwrite-splitting:
#        data-sources:
#          glapp:
#            write-data-source-name: master
#            read-data-source-name: slave
#            load-balancer-name: roundRobin # 负载均衡算法名称
#        load-balancers:
#          roundRobin:
#            type: ROUND_ROBIN # 一共两种一种是 RANDOM（随机），一种是 ROUND_ROBIN（轮询）

# 开启MyBatis打印日志
#logging:
#  level:
#    com.shardingsphere: debug
