server:
  port: 8002
spring:
  shardingsphere:
    props:
      sql-show: true
    mode:
      type: Memory
    datasource:
      names: master,slave
      master:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://139.196.112.185:3307/TEST-01?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&useSSL=false
        username: root
        password: 123456
      slave:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://139.196.112.185:3308/TEST-01?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&useSSL=false
        username: root
        password: 123456
      enabled: true
    rules:
      readwrite-splitting:
        data-sources:
          load-balancers:
            roundRobin:
              type: ROUND_ROBIN
          master-slave:
            props:
              auto-aware-data-source-name: master
              load-balancers-names: roundRobin
              read-data-source-names: slave
              write-data-source-name: master
            type: Static
#    rules:
#      readwrite-splitting:
#        data-sources:
#          glapp:
#            write-data-source-name: master
#            read-data-source-name: slave
#            load-balancer-name: roundRobin # 负载均衡算法名称
#        load-balancers:
#          roundRobin:
#            type: ROUND_ROBIN # 一共两种一种是 RANDOM（随机），一种是 ROUND_ROBIN（轮询）

# 开启MyBatis打印日志
#logging:
#  level:
#    com.shardingsphere: debug
